spring:
  application:
    name: demo
    spring:
      jackson:
        serialization:
          write-dates-as-timestamps: false
          spring:
            jpa:
              properties:
                hibernate:
                  default_batch_fetch_size: 10


  datasource:
    url: jdbc:postgresql://localhost:5432/customer_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: true
server:
  port: 9090



